### ISSUE TITLE
model trained with discharge summary cannnot be downloaded

### ISSUE THREAD

**Issue by FacingBugs** [kexinhuang12345/clinicalXLNet#1]
After clicking the link for XLNet model trained with the discharge summary notes, I got the following response:

![Screen Shot 2020-01-03 at 08 40 00](https://user-images.githubusercontent.com/16659741/71726313-b9ca2100-2e04-11ea-8f8b-9d1d55b3978d.jpg)

**Comment by kexinhuang12345** [comment]
https://hu-my.sharepoint.com/:u:/g/personal/kexinhuang_hsph_harvard_edu/ERPrsMddJMhDoltA5EniFk8BkLKoRF3O5JmYfCThvG3ctQ?e=Fe6zmi

Now should be good.
